service:
  name: ${env:STAGE}-${env:REGION}-${env:APP_NAME}
custom:
  dotenv:
    basePath: environments/
    exclude: # By default dotenv will add the env to your functions
      - ACCESS_KEY_ID
      - SECRET_ACCESS_KEY 
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: ${env:API_DOMAIN}
    certificateName: ${env:API_DOMAIN}
    createRoute53Record: true
    endpointType: 'edge'
    securityPolicy: tls_1_2
    hostedZoneId: ${env:HOSTED_ZONE_ID}
    apiType: rest
    autoDomain: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
  
provider:
  name: aws
  region: ${env:REGION, 'us-east-1'}
  stage: ${env:STAGE, 'dev'}
  stackName: ${self:service.name}-stack
  runtime: nodejs12.x
  tracing:
    apiGateway: true
    lambda: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_ENV: dev

resources:
- Resources:
- ${file(iac/resources/cognito.serverless.yml)}

functions:
  base:
    handler: src/app.app_bundle
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

